### ISSUE TITLE
Some pages error display in dark mode & a suggestion

### ISSUE THREAD

**Issue by taozhiyu** [Fentaniao/Liquid#3]
Overall, of course, the theme is stunning!

I love it so much, and I found some mistake in dark mode.

Here're my suggestions and the mistake I found below

## setting page

There are some errors in the display of the window title and the history file list.

Here's screenshot below

![image](https://user-images.githubusercontent.com/49258735/149949206-d16f2126-f107-426d-a843-d45ae5efe1ec.png)

PS. The display in `menu button` on the right is also wrong, forgot to mark it on the shot

## typing page

error display in code block 

![image](https://user-images.githubusercontent.com/49258735/149949906-b6975e9b-c055-4212-8419-95fd25fd8e4d.png)

## some Tips

![image](https://user-images.githubusercontent.com/49258735/149961881-a5c6d1bb-db47-4f5a-bff1-0d47b190edbf.png)

As what shows in the screenshot above, I noticed that the official themes use `@font-face` and `url` in CSS to define font family instead of install the suggested font globally into our PC, I think it might work in a more friendly way.

**Comment by ruiyangzhou01** [comment]
Thank you very much for your issue, I will deal with these problems soon.

**Comment by ruiyangzhou01** [comment]
The problems you mentioned now have been fixed in Release v0.3.3.

Release v0.3.3 has mainly fixed bugs and improved the visual effect in Dark Mode.

Thanks for your feedback and advice.
