### ISSUE TITLE
Display error in dark mode

### ISSUE THREAD

**Issue by taozhiyu** [Fentaniao/Liquid#4]
![image](https://user-images.githubusercontent.com/49258735/150639592-1f6428e2-e2a4-4cd8-a866-d2b89b27d6bb.png)

The background color of the button `Exit Source Code Mode` in the bottom is too bright to read the text

**Comment by ruiyangzhou01** [comment]
Thank you very much for your issue, I will deal with these problems soon.

**Comment by ruiyangzhou01** [comment]
The problems you mentioned now have been fixed in Release v0.3.4.

Release v0.3.4 has mainly fixed bugs in Dark Mode.

Thanks for your feedback and advice.

**Comment by ruiyangzhou01** [comment]
Sorry to disturb you, are you the moderator ""涛之雨 in "吾爱破解论坛"? @taozhiyu

**Comment by taozhiyu** [comment]
@Fentaniao 

是的，看来应该是国人了，我就直接用中文了哈哈哈哈

没有收到@提醒，所以刚看见（因为又要来提issue了）

**Comment by ruiyangzhou01** [comment]
@taozhiyu 哈哈，大佬可以留个联系方式认识一下吗？

**Comment by taozhiyu** [comment]
> @taozhiyu 哈哈，大佬可以留个联系方式认识一下吗？

（其实我发邮件给你了，不知道你有没有收到）

**Comment by Fentaniao** [comment]
邮件已收到，不过我之前一直认为这是GitHub自动发送的，所以没有注意

**Comment by ruiyangzhou01** [comment]
我过了一天才明白你私发了邮件给我。这封邮件不幸进了垃圾邮件列表，所以我没有收到。

我已经发出添加申请了。
